"""Playwright-compatible page protocol used by the supervised runner.

Deliberately narrow. Notably there is **no** method to solve challenges, read
inbox codes, rotate transport, or alter the automation surface. The runner can
navigate, read, fill allowlisted inputs, click named controls, upload approved
files, and screenshot — nothing else.
"""
from __future__ import annotations

from typing import Protocol


class BrowserPage(Protocol):
    async def goto(self, url: str) -> None: ...
    async def current_url(self) -> str: ...
    async def content(self) -> str: ...
    async def is_visible(self, selector: str) -> bool: ...
    async def text_content(self, selector: str) -> str | None: ...
    async def fill(self, selector: str, value: str) -> None: ...
    async def click(self, selector: str) -> None: ...
    async def check(self, selector: str) -> None: ...
    async def select_option(self, selector: str, value: str) -> None: ...
    async def set_input_files(self, selector: str, path: str) -> None: ...
    async def screenshot(self, *, path: str) -> bytes: ...
