"""Assisted-application sandbox: mock ATS board plus a pausable autofill runner."""

from .mock_ats import (
    ALLOWED_MOCK_FIELDS,
    MOCK_ATS_FORM,
    MOCK_ATS_LABEL,
    MOCK_ATS_URL_PREFIX,
    MockAtsError,
    assert_mock_target,
    board_token,
    confirmation_code,
    form_definition,
    is_mock_target,
    mock_ats_url,
    validate_payload,
)
from .runner import (
    PAUSED,
    QUEUED,
    RUNNING,
    STOPPED_BEFORE_SUBMIT,
    TERMINAL_ACTION,
    RunnerError,
    assert_advanceable,
    assert_pausable,
    assert_resumable,
    build_plan,
    execute_step,
    next_status,
)
from .submissions import build_idempotency_key, record_submission

__all__ = [
    "build_idempotency_key",
    "record_submission",
    "ALLOWED_MOCK_FIELDS",
    "MOCK_ATS_FORM",
    "MOCK_ATS_LABEL",
    "MOCK_ATS_URL_PREFIX",
    "MockAtsError",
    "PAUSED",
    "QUEUED",
    "RUNNING",
    "STOPPED_BEFORE_SUBMIT",
    "TERMINAL_ACTION",
    "RunnerError",
    "assert_advanceable",
    "assert_mock_target",
    "assert_pausable",
    "assert_resumable",
    "board_token",
    "build_plan",
    "confirmation_code",
    "execute_step",
    "form_definition",
    "is_mock_target",
    "mock_ats_url",
    "next_status",
    "validate_payload",
]
